const questions = [
  {
    "question": "I am not afraid of anyone.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I am not afraid of anything.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I am not afraid of death.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "The plight of those struck by misfortune evokes compassion in me.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I deeply value matters that are <br>important to me as a person.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I constantly endeavour to assess my life in terms of things I cherish.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "It is my personal goal to change and always grow as a person. ",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I constantly seek learning from my experiences.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I do not get easily unsettled by inconsiderate words or actions of others.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I do not get carried away by praise or recognition for myself.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": "I do not get carried away when I get what I want in my life.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  },
  {
    "question": " I do not feel bogged down when things are not going well for me.",
    "answer1": "Totally Disagree",
    "answer1Total": "1",
    "answer2": "Disagree",
    "answer2Total": "2",
    "answer3": "Neutral",
    "answer3Total": "3",
    "answer4": "Agree",
    "answer4Total": "4",
    "answer5": "Totally Agree",
    "answer5Total": "5"
  }
]
